# Generated by Django 3.0.7 on 2020-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qaconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaconnid', models.CharField(max_length=50, null=True)),
                ('systemtype', models.CharField(max_length=10, null=True)),
                ('ipaddress', models.CharField(max_length=15, null=True)),
                ('port', models.CharField(max_length=5, null=True)),
                ('adminuser', models.CharField(max_length=25, null=True)),
                ('adminpass', models.CharField(max_length=30, null=True)),
                ('sysid', models.CharField(max_length=2, null=True)),
                ('client', models.CharField(max_length=3, null=True)),
                ('githuburl', models.CharField(max_length=100, null=True)),
                ('triggerrate', models.CharField(max_length=3, null=True)),
                ('triggeruom', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
