# Generated by Django 3.0.7 on 2020-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QALog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QALogID', models.CharField(max_length=120)),
                ('SystemType', models.CharField(max_length=120)),
                ('QAConnID', models.CharField(max_length=120)),
                ('QACreatedDate', models.CharField(max_length=120)),
                ('JIRALogFlag', models.CharField(max_length=120)),
                ('QALog', models.CharField(max_length=120)),
                ('QALoggedDate', models.CharField(max_length=120)),
            ],
        ),
    ]
