# Generated by Django 3.0.7 on 2020-07-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qalog',
            name='QALog',
            field=models.CharField(max_length=10000),
        ),
    ]
