# Generated by Django 3.0.7 on 2020-07-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qalog', '0003_auto_20200721_1130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qalog',
            unique_together={('QAConnID', 'ObjectPath', 'QACreatedDate')},
        ),
    ]
