# Generated by Django 3.0.7 on 2020-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('user', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('countrycode', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
